---
label: default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: image
  label: image
- type: text
  name: layout
  label: layout
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
pages:
- _posts/amazing-grace-film-2019-full-download.md
- _posts/2019-05-13-the-souvenir-full-movie-2019.md
